### ISSUE TITLE
TestConcludeSimulatedBackendChainService flicker: time out 

### ISSUE THREAD

**Issue by lalexgap** [statechannels/go-nitro#1137]
See https://github.com/statechannels/go-nitro/actions/runs/4256263642/jobs/7404916092

```
2023-02-23T19:46:04.2585460Z ##[group]Run go test ./... -count=2 -shuffle=on -timeout 1m
2023-02-23T19:46:04.2585805Z [36;1mgo test ./... -count=2 -shuffle=on -timeout 1m[0m
2023-02-23T19:46:04.2637939Z shell: /usr/bin/bash -e {0}
2023-02-23T19:46:04.2638174Z ##[endgroup]
2023-02-23T19:46:04.8131476Z ?   	github.com/statechannels/go-nitro/abi	[no test files]
2023-02-23T19:46:05.3377159Z ok  	github.com/statechannels/go-nitro/channel	0.024s
2023-02-23T19:46:05.5277883Z ok  	github.com/statechannels/go-nitro/channel/consensus_channel	0.173s
2023-02-23T19:46:05.6890092Z ok  	github.com/statechannels/go-nitro/channel/state	0.026s
2023-02-23T19:46:05.9539591Z ok  	github.com/statechannels/go-nitro/channel/state/outcome	0.017s
2023-02-23T19:46:05.9589164Z ?   	github.com/statechannels/go-nitro/client	[no test files]
2023-02-23T19:46:05.9589936Z ?   	github.com/statechannels/go-nitro/client/engine	[no test files]
2023-02-23T19:47:06.7740626Z -test.shuffle 1677181566766193673
2023-02-23T19:47:06.7741449Z panic: test timed out after 1m0s
2023-02-23T19:47:06.7741752Z 
2023-02-23T19:47:06.7831077Z goroutine 32 [running]:
2023-02-23T19:47:06.7831360Z testing.(*M).startAlarm.func1()
2023-02-23T19:47:06.7833657Z 	/opt/hostedtoolcache/go/1.19.6/x64/src/testing/testing.go:2036 +0x8e
2023-02-23T19:47:06.7833985Z created by time.goFunc
2023-02-23T19:47:06.7834356Z 	/opt/hostedtoolcache/go/1.19.6/x64/src/time/sleep.go:176 +0x32
2023-02-23T19:47:06.7834554Z 
2023-02-23T19:47:06.7834673Z goroutine 1 [chan receive]:
2023-02-23T19:47:06.7834992Z testing.(*T).Run(0xc0002fe340, {0xb1404d?, 0x519b45?}, 0xce7488)
2023-02-23T19:47:06.7835437Z 	/opt/hostedtoolcache/go/1.19.6/x64/src/testing/testing.go:1494 +0x37a
2023-02-23T19:47:06.7835769Z testing.runTests.func1(0xc0002fe340?)
2023-02-23T19:47:06.7836163Z 	/opt/hostedtoolcache/go/1.19.6/x64/src/testing/testing.go:1846 +0x6e
2023-02-23T19:47:06.7836505Z testing.tRunner(0xc0002fe340, 0xc000261cd8)
2023-02-23T19:47:06.7836909Z 	/opt/hostedtoolcache/go/1.19.6/x64/src/testing/testing.go:1446 +0x10b
2023-02-23T19:47:06.7837296Z testing.runTests(0xc0000b39a0?, {0x1119dc0, 0x6, 0x6}, {0x2?, 0x40?, 0x1168620?})
2023-02-23T19:47:06.7837723Z 	/opt/hostedtoolcache/go/1.19.6/x64/src/testing/testing.go:1844 +0x456
2023-02-23T19:47:06.7838029Z testing.(*M).Run(0xc0000b39a0)
2023-02-23T19:47:06.7838401Z 	/opt/hostedtoolcache/go/1.19.6/x64/src/testing/testing.go:1726 +0x5d9
2023-02-23T19:47:06.7838675Z main.main()
2023-02-23T19:47:06.7838949Z 	_testmain.go:57 +0x1aa
2023-02-23T19:47:06.7839090Z 
2023-02-23T19:47:06.7839210Z goroutine 18 [chan receive]:
2023-02-23T19:47:06.7839572Z github.com/rjeczalik/notify.(*nonrecursiveTree).dispatch(0xc0000ad0e0, 0x0?)
2023-02-23T19:47:06.7840084Z 	/home/runner/go/pkg/mod/github.com/rjeczalik/notify@v0.9.1/tree_nonrecursive.go:36 +0x45
2023-02-23T19:47:06.7840499Z created by github.com/rjeczalik/notify.newNonrecursiveTree
2023-02-23T19:47:06.7840981Z 	/home/runner/go/pkg/mod/github.com/rjeczalik/notify@v0.9.1/tree_nonrecursive.go:29 +0x16a
2023-02-23T19:47:06.7841209Z 
2023-02-23T19:47:06.7841333Z goroutine 19 [chan receive]:
2023-02-23T19:47:06.7841703Z github.com/rjeczalik/notify.(*nonrecursiveTree).internal(0xc0000ad0e0, 0xc0000ad080)
2023-02-23T19:47:06.7842210Z 	/home/runner/go/pkg/mod/github.com/rjeczalik/notify@v0.9.1/tree_nonrecursive.go:81 +0x5a
2023-02-23T19:47:06.7842615Z created by github.com/rjeczalik/notify.newNonrecursiveTree
2023-02-23T19:47:06.7843090Z 	/home/runner/go/pkg/mod/github.com/rjeczalik/notify@v0.9.1/tree_nonrecursive.go:30 +0x1be
2023-02-23T19:47:06.7843314Z 
2023-02-23T19:47:06.7843431Z goroutine 20 [chan receive]:
2023-02-23T19:47:06.7843958Z github.com/ethereum/go-ethereum/metrics.(*meterArbiter).tick(0x1168080)
2023-02-23T19:47:06.7844564Z 	/home/runner/go/pkg/mod/github.com/ethereum/go-ethereum@v1.10.26/metrics/meter.go:290 +0x65
2023-02-23T19:47:06.7845048Z created by github.com/ethereum/go-ethereum/metrics.NewMeterForced
2023-02-23T19:47:06.7845923Z 	/home/runner/go/pkg/mod/github.com/ethereum/go-ethereum@v1.10.26/metrics/meter.go:71 +0xc5
2023-02-23T19:47:06.7846198Z 
2023-02-23T19:47:06.7846313Z goroutine 21 [select]:
2023-02-23T19:47:06.7846760Z github.com/ethereum/go-ethereum/consensus/ethash.(*remoteSealer).loop(0xc0000cd3b0)
2023-02-23T19:47:06.7847404Z 	/home/runner/go/pkg/mod/github.com/ethereum/go-ethereum@v1.10.26/consensus/ethash/sealer.go:279 +0x205
2023-02-23T19:47:06.7847937Z created by github.com/ethereum/go-ethereum/consensus/ethash.startRemoteSealer
2023-02-23T19:47:06.7848569Z 	/home/runner/go/pkg/mod/github.com/ethereum/go-ethereum@v1.10.26/consensus/ethash/sealer.go:263 +0x319
2023-02-23T19:47:06.7848908Z 
2023-02-23T19:47:06.7849029Z goroutine 22 [chan receive]:
2023-02-23T19:47:06.7849436Z github.com/ethereum/go-ethereum/core.(*txSenderCacher).cache(0x0?)
2023-02-23T19:47:06.7850018Z 	/home/runner/go/pkg/mod/github.com/ethereum/go-ethereum@v1.10.26/core/tx_cacher.go:63 +0x3b
2023-02-23T19:47:06.7850495Z created by github.com/ethereum/go-ethereum/core.newTxSenderCacher
2023-02-23T19:47:06.7851075Z 	/home/runner/go/pkg/mod/github.com/ethereum/go-ethereum@v1.10.26/core/tx_cacher.go:55 +0x75
2023-02-23T19:47:06.7851298Z 
2023-02-23T19:47:06.7851413Z goroutine 23 [chan receive]:
2023-02-23T19:47:06.7851816Z github.com/ethereum/go-ethereum/core.(*txSenderCacher).cache(0x0?)
2023-02-23T19:47:06.7852384Z 	/home/runner/go/pkg/mod/github.com/ethereum/go-ethereum@v1.10.26/core/tx_cacher.go:63 +0x3b
2023-02-23T19:47:06.7852857Z created by github.com/ethereum/go-ethereum/core.newTxSenderCacher
2023-02-23T19:47:06.7853426Z 	/home/runner/go/pkg/mod/github.com/ethereum/go-ethereum@v1.10.26/core/tx_cacher.go:55 +0x75
2023-02-23T19:47:06.7853654Z 
2023-02-23T19:47:06.7853768Z goroutine 24 [chan receive]:
2023-02-23T19:47:06.7854298Z github.com/statechannels/go-nitro/client/engine/chainservice.runDepositAndConcludeTest(0xc0002fe4e0, 0x0)
2023-02-23T19:47:06.7855022Z 	/home/runner/work/go-nitro/go-nitro/client/engine/chainservice/simulated_backend_chainservice_test.go:145 +0x974
2023-02-23T19:47:06.7855693Z github.com/statechannels/go-nitro/client/engine/chainservice.TestConcludeSimulatedBackendChainService(0x0?)
2023-02-23T19:47:06.7856433Z 	/home/runner/work/go-nitro/go-nitro/client/engine/chainservice/simulated_backend_chainservice_test.go:90 +0x1b
2023-02-23T19:47:06.7856818Z testing.tRunner(0xc0002fe4e0, 0xce7488)
2023-02-23T19:47:06.7857217Z 	/opt/hostedtoolcache/go/1.19.6/x64/src/testing/testing.go:1446 +0x10b
2023-02-23T19:47:06.7857520Z created by testing.(*T).Run
2023-02-23T19:47:06.7858140Z 	/opt/hostedtoolcache/go/1.19.6/x64/src/testing/testing.go:1493 +0x35f
2023-02-23T19:47:06.7858344Z 
2023-02-23T19:47:06.7858460Z goroutine 7 [chan receive]:
2023-02-23T19:47:06.7858959Z github.com/ethereum/go-ethereum/core/state/snapshot.(*diskLayer).generate(0xc00017a000, 0xc0003c8880)
2023-02-23T19:47:06.7859638Z 	/home/runner/go/pkg/mod/github.com/ethereum/go-ethereum@v1.10.26/core/state/snapshot/generate.go:719 +0x5b7
2023-02-23T19:47:06.7860183Z created by github.com/ethereum/go-ethereum/core/state/snapshot.generateSnapshot
2023-02-23T19:47:06.7860841Z 	/home/runner/go/pkg/mod/github.com/ethereum/go-ethereum@v1.10.26/core/state/snapshot/generate.go:86 +0x385
2023-02-23T19:47:06.7861087Z 
2023-02-23T19:47:06.7861191Z goroutine 8 [select]:
2023-02-23T19:47:06.7861639Z github.com/ethereum/go-ethereum/core.(*BlockChain).updateFutureBlocks(0xc00046c000)
2023-02-23T19:47:06.7862265Z 	/home/runner/go/pkg/mod/github.com/ethereum/go-ethereum@v1.10.26/core/blockchain.go:2224 +0x110
2023-02-23T19:47:06.7862741Z created by github.com/ethereum/go-ethereum/core.NewBlockChain
2023-02-23T19:47:06.7863328Z 	/home/runner/go/pkg/mod/github.com/ethereum/go-ethereum@v1.10.26/core/blockchain.go:389 +0x1dad
2023-02-23T19:47:06.7863553Z 
2023-02-23T19:47:06.7863673Z goroutine 9 [chan receive]:
2023-02-23T19:47:06.7864541Z github.com/ethereum/go-ethereum/accounts/abi/bind/backends.(*filterBackend).SubscribeNewTxsEvent.func1(0x0?)
2023-02-23T19:47:06.7865260Z 	/home/runner/go/pkg/mod/github.com/ethereum/go-ethereum@v1.10.26/accounts/abi/bind/backends/simulated.go:895 +0x1b
2023-02-23T19:47:06.7865878Z github.com/ethereum/go-ethereum/event.NewSubscription.func1()
2023-02-23T19:47:06.7866490Z 	/home/runner/go/pkg/mod/github.com/ethereum/go-ethereum@v1.10.26/event/subscription.go:53 +0x62
2023-02-23T19:47:06.7866983Z created by github.com/ethereum/go-ethereum/event.NewSubscription
2023-02-23T19:47:06.7867570Z 	/home/runner/go/pkg/mod/github.com/ethereum/go-ethereum@v1.10.26/event/subscription.go:51 +0xed
2023-02-23T19:47:06.7867796Z 
2023-02-23T19:47:06.7867917Z goroutine 10 [chan receive]:
2023-02-23T19:47:06.7868525Z github.com/ethereum/go-ethereum/accounts/abi/bind/backends.(*filterBackend).SubscribePendingLogsEvent.func1(0x0?)
2023-02-23T19:47:06.7869241Z 	/home/runner/go/pkg/mod/github.com/ethereum/go-ethereum@v1.10.26/accounts/abi/bind/backends/simulated.go:895 +0x1b
2023-02-23T19:47:06.7869750Z github.com/ethereum/go-ethereum/event.NewSubscription.func1()
2023-02-23T19:47:06.7870344Z 	/home/runner/go/pkg/mod/github.com/ethereum/go-ethereum@v1.10.26/event/subscription.go:53 +0x62
2023-02-23T19:47:06.7870831Z created by github.com/ethereum/go-ethereum/event.NewSubscription
2023-02-23T19:47:06.7871427Z 	/home/runner/go/pkg/mod/github.com/ethereum/go-ethereum@v1.10.26/event/subscription.go:51 +0xed
2023-02-23T19:47:06.7871647Z 
2023-02-23T19:47:06.7871754Z goroutine 11 [select]:
2023-02-23T19:47:06.7872187Z github.com/ethereum/go-ethereum/eth/filters.(*EventSystem).eventLoop(0xc00011a790)
2023-02-23T19:47:06.7872820Z 	/home/runner/go/pkg/mod/github.com/ethereum/go-ethereum@v1.10.26/eth/filters/filter_system.go:538 +0x40c
2023-02-23T19:47:06.7873327Z created by github.com/ethereum/go-ethereum/eth/filters.NewEventSystem
2023-02-23T19:47:06.7873965Z 	/home/runner/go/pkg/mod/github.com/ethereum/go-ethereum@v1.10.26/eth/filters/filter_system.go:217 +0x3aa
2023-02-23T19:47:06.7874203Z 
2023-02-23T19:47:06.7874310Z goroutine 30 [select]:
2023-02-23T19:47:06.7874885Z github.com/statechannels/go-nitro/client/engine/chainservice.(*EthChainService).subscribeForLogs(0xc0001a51e0, {0xdaadf0, 0xc0000380d0})
2023-02-23T19:47:06.7875557Z 	/home/runner/work/go-nitro/go-nitro/client/engine/chainservice/eth_chainservice.go:261 +0x2b7
2023-02-23T19:47:06.7876116Z created by github.com/statechannels/go-nitro/client/engine/chainservice.NewEthChainService
2023-02-23T19:47:06.7876749Z 	/home/runner/work/go-nitro/go-nitro/client/engine/chainservice/eth_chainservice.go:76 +0x85d
2023-02-23T19:47:06.7876982Z 
2023-02-23T19:47:06.7877085Z goroutine 31 [select]:
2023-02-23T19:47:06.7877632Z github.com/ethereum/go-ethereum/accounts/abi/bind/backends.(*SimulatedBackend).SubscribeFilterLogs.func1(0xc00074ff80)
2023-02-23T19:47:06.7878359Z 	/home/runner/go/pkg/mod/github.com/ethereum/go-ethereum@v1.10.26/accounts/abi/bind/backends/simulated.go:737 +0x151
2023-02-23T19:47:06.7878877Z github.com/ethereum/go-ethereum/event.NewSubscription.func1()
2023-02-23T19:47:06.7879466Z 	/home/runner/go/pkg/mod/github.com/ethereum/go-ethereum@v1.10.26/event/subscription.go:53 +0x62
2023-02-23T19:47:06.7879950Z created by github.com/ethereum/go-ethereum/event.NewSubscription
2023-02-23T19:47:06.7880531Z 	/home/runner/go/pkg/mod/github.com/ethereum/go-ethereum@v1.10.26/event/subscription.go:51 +0xed
2023-02-23T19:47:06.7881042Z FAIL	github.com/statechannels/go-nitro/client/engine/chainservice	60.028s
2023-02-23T19:47:06.7881553Z ok  	github.com/statechannels/go-nitro/client/engine/chainservice/adjudicator	0.157s
2023-02-23T19:47:06.7882099Z ?   	github.com/statechannels/go-nitro/client/engine/chainservice/consensusapp	[no test files]
2023-02-23T19:47:06.7882651Z ok  	github.com/statechannels/go-nitro/client/engine/chainservice/create2deployer	0.067s
2023-02-23T19:47:06.7883179Z ?   	github.com/statechannels/go-nitro/client/engine/chainservice/erc20	[no test files]
2023-02-23T19:47:06.7883741Z ?   	github.com/statechannels/go-nitro/client/engine/chainservice/virtualpaymentapp	[no test files]
2023-02-23T19:47:06.7884259Z ok  	github.com/statechannels/go-nitro/client/engine/messageservice	0.015s
2023-02-23T19:47:06.7884885Z ?   	github.com/statechannels/go-nitro/client/engine/messageservice/p2p-message-service	[no test files]
2023-02-23T19:47:06.7885387Z ok  	github.com/statechannels/go-nitro/client/engine/store	0.032s
2023-02-23T19:47:06.7885874Z ?   	github.com/statechannels/go-nitro/client/engine/store/safesync	[no test files]
2023-02-23T19:47:06.7886335Z ?   	github.com/statechannels/go-nitro/client/query	[no test files]
2023-02-23T19:47:06.7886762Z ok  	github.com/statechannels/go-nitro/client_test	5.938s
2023-02-23T19:47:06.7887182Z ?   	github.com/statechannels/go-nitro/crypto	[no test files]
2023-02-23T19:47:06.7887685Z ?   	github.com/statechannels/go-nitro/internal/logging	[no test files]
2023-02-23T19:47:06.7888152Z ?   	github.com/statechannels/go-nitro/internal/testactors	[no test files]
2023-02-23T19:47:06.7888628Z ?   	github.com/statechannels/go-nitro/internal/testhelpers	[no test files]
2023-02-23T19:47:06.7889056Z ok  	github.com/statechannels/go-nitro/payments	0.019s
2023-02-23T19:47:06.7889470Z ok  	github.com/statechannels/go-nitro/protocols	0.015s
2023-02-23T19:47:06.7889911Z ok  	github.com/statechannels/go-nitro/protocols/directdefund	0.063s
2023-02-23T19:47:06.7890373Z ok  	github.com/statechannels/go-nitro/protocols/directfund	0.039s
2023-02-23T19:47:06.7890839Z ok  	github.com/statechannels/go-nitro/protocols/virtualdefund	0.073s
2023-02-23T19:47:06.7891304Z ok  	github.com/statechannels/go-nitro/protocols/virtualfund	0.319s
2023-02-23T19:47:06.7891731Z ?   	github.com/statechannels/go-nitro/rpc	[no test files]
2023-02-23T19:47:06.7892170Z ?   	github.com/statechannels/go-nitro/rpc/network	[no test files]
2023-02-23T19:47:06.7892586Z ok  	github.com/statechannels/go-nitro/rpc/serde	0.019s
2023-02-23T19:47:06.7893021Z ?   	github.com/statechannels/go-nitro/rpc/transport	[no test files]
2023-02-23T19:47:06.7893483Z ?   	github.com/statechannels/go-nitro/rpc/transport/nats	[no test files]
2023-02-23T19:47:06.7893948Z ?   	github.com/statechannels/go-nitro/rpc/transport/ws	[no test files]
2023-02-23T19:47:06.7894369Z ok  	github.com/statechannels/go-nitro/types	0.003s
2023-02-23T19:47:06.7894621Z FAIL
2023-02-23T19:47:06.7927990Z ##[error]Process completed with exit code 1.
```

**Comment by lalexgap** [comment]
Another one https://github.com/statechannels/go-nitro/actions/runs/4256453130/jobs/7405357914

**Comment by kerzhner** [comment]
`TestConcludeSimulatedBackendChainService` times out in the logs. It is unclear which channel receive is causing the timeout.
