### ISSUE TITLE
The websocket RPC Server crashes if there are no listeners

### ISSUE THREAD

**Issue by lalexgap** [statechannels/go-nitro#1208]
The RPC server may crash if it completes an objective and there are no RPC clients listening for JSON-RPC notifications with the following error:
```
{"l":"trace","client":"0xBBB676f9cFF8D242e9eaC39D063848807d3D1D94","rpc":"server","scope":"","t":1680892402,"m":"Sending notification: DirectFunding-0x4fd071df208b69c95d267401925445810455ddf811bb87637709de934fb49e03"}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x100 pc=0x104fd3974]

goroutine 119 [running]:
nhooyr.io/websocket.(*Conn).writer(0x0, {0x1058ed3b0?, 0x14000196000?}, 0x0?)
	/Users/lagap/go/pkg/mod/nhooyr.io/websocket@v1.8.7/write.go:111 +0x24
nhooyr.io/websocket.(*Conn).write(0x0, {0x1058ed3b0, 0x14000196000}, 0x40?, {0x140005d2370, 0xa5, 0xb0})
	/Users/lagap/go/pkg/mod/nhooyr.io/websocket@v1.8.7/write.go:122 +0x48
nhooyr.io/websocket.(*Conn).Write(0x140005d2370?, {0x1058ed3b0?, 0x14000196000?}, 0x10474bed0?, {0x140005d2370?, 0x1058a7200?, 0x14000175300?})
	/Users/lagap/go/pkg/mod/nhooyr.io/websocket@v1.8.7/write.go:42 +0x28
github.com/statechannels/go-nitro/rpc/transport/ws.(*serverWebSocketTransport).Notify(0x105697a20?, {0x140005d2370?, 0x0?, 0x140000e6fb8?})
	/Users/lagap/code/go-nitro/rpc/transport/ws/server.go:63 +0x4c
github.com/statechannels/go-nitro/rpc.(*RpcServer).sendNotifications.func1()
	/Users/lagap/code/go-nitro/rpc/server.go:201 +0x160
created by github.com/statechannels/go-nitro/rpc.(*RpcServer).sendNotifications
	/Users/lagap/code/go-nitro/rpc/server.go:193 +0x60
exit status 2
```
I'm running into this error in the following scenario:
- Spin up RPC server for Alice
- Spin up RPC server for Bob
- Spin up a (typescript) RPC client for Alice
- Create a directly funded channel via Alice's  RPC client

We then get the error above in Bob's RPC server when the direct fund objective completes.

 Ideally the rpc server would be able to handle the case where are there no notification listeners gracefully instead of blowing up.

**Comment by kerzhner** [comment]
Thanks for pointing out this issue. I am working on a fix.

Would you mind clarifying the reason an rpc server is spun up for Bob? Is it easer to spin up a go-nitro node instead of an rpc server.
