### ISSUE TITLE
There is no way for an WebSocket RPC client to graceully stop using an RPC Server

### ISSUE THREAD

**Issue by lalexgap** [statechannels/go-nitro#1209]
Currently there is no way for an RPC client to stop using the RPC server without crashing the server.

Exiting the typescript client without closing the websocket causes this error on the RPC server:
```
2023/04/07 11:48:31 http: panic serving 127.0.0.1:62674: failed to get reader: failed to read frame header: EOF
goroutine 148 [running]:
net/http.(*conn).serve.func1()
	/opt/homebrew/Cellar/go/1.20.3/libexec/src/net/http/server.go:1854 +0xb0
panic({0x1015ae780, 0x14000892360})
	/opt/homebrew/Cellar/go/1.20.3/libexec/src/runtime/panic.go:890 +0x258
github.com/statechannels/go-nitro/rpc/transport/ws.(*serverWebSocketTransport).subscribeRequestHandler(0x140002a0270, {0x101760070?, 0x1400074e1c0?}, 0x140008a4600)
	/Users/lagap/code/go-nitro/rpc/transport/ws/server.go:93 +0x1a8
net/http.HandlerFunc.ServeHTTP(0x0?, {0x101760070?, 0x1400074e1c0?}, 0xffffffffffffffff?)
	/opt/homebrew/Cellar/go/1.20.3/libexec/src/net/http/server.go:2122 +0x38
net/http.(*ServeMux).ServeHTTP(0x10?, {0x101760070, 0x1400074e1c0}, 0x140008a4600)
	/opt/homebrew/Cellar/go/1.20.3/libexec/src/net/http/server.go:2500 +0x140
github.com/statechannels/go-nitro/rpc/transport/ws.(*serverWebSocketTransport).ServeHTTP(0x0?, {0x101760070?, 0x1400074e1c0?}, 0x100761518?)
	/Users/lagap/code/go-nitro/rpc/transport/ws/server.go:54 +0x28
net/http.serverHandler.ServeHTTP({0x140008bbaa0?}, {0x101760070, 0x1400074e1c0}, 0x140008a4600)
	/opt/homebrew/Cellar/go/1.20.3/libexec/src/net/http/server.go:2936 +0x2d8
net/http.(*conn).serve(0x1400077b560, {0x101761420, 0x14000174420})
	/opt/homebrew/Cellar/go/1.20.3/libexec/src/net/http/server.go:1995 +0x560
created by net/http.(*Server).Serve
	/opt/homebrew/Cellar/go/1.20.3/libexec/src/net/http/server.go:3089 +0x520
```

If we try to close the websocket on the client before exiting we get this error on the RPC server.
```
panic: failed to write msg: WebSocket closed: received close frame: status = StatusNoStatusRcvd and reason = ""
goroutine 116 [running]:
github.com/statechannels/go-nitro/rpc.(*RpcServer).sendNotifications.func1()
	/Users/lagap/code/go-nitro/rpc/server.go:204 +0x180
created by github.com/statechannels/go-nitro/rpc.(*RpcServer).sendNotifications
	/Users/lagap/code/go-nitro/rpc/server.go:193 +0x60
exit status 2
```

**Comment by kerzhner** [comment]
Would you mind including repro steps for this issue so that I can take a look and debug?

**Comment by lalexgap** [comment]
> Would you mind including repro steps for this issue so that I can take a look and debug?

I'll take a look at retesting this once the typescript rpc client has been updated to use ws/http. If I'm still seeing it I'll attach repro steps.

**Comment by lalexgap** [comment]
I think this can be closed now.
