### ISSUE TITLE
NitroAAS crashes when we forcibly kill the rpc client (connected by websockets) 

### ISSUE THREAD

**Issue by geoknee** [statechannels/go-nitro#1258]

**Comment by geoknee** [comment]
```
2023/05/05 17:44:47 http: panic serving 127.0.0.1:62103: failed to get reader: failed to read frame header: EOF
goroutine 139 [running]:
net/http.(*conn).serve.func1()
	/usr/local/go/src/net/http/server.go:1854 +0xb0
panic({0x1036e9420, 0x14000130a40})
	/usr/local/go/src/runtime/panic.go:890 +0x258
github.com/statechannels/go-nitro/rpc/transport/ws.(*serverWebSocketTransport).subscribe(0x14000699ec0, {0x1038f9b80?, 0x140006500e0?}, 0x1400035c100)
	/Users/georgeknee/statechannels/go-nitro/rpc/transport/ws/server.go:151 +0x454
net/http.HandlerFunc.ServeHTTP(0x140004fcad8?, {0x1038f9b80?, 0x140006500e0?}, 0x10?)
	/usr/local/go/src/net/http/server.go:2122 +0x38
net/http.(*ServeMux).ServeHTTP(0x0?, {0x1038f9b80, 0x140006500e0}, 0x1400035c100)
	/usr/local/go/src/net/http/server.go:2500 +0x140
net/http.serverHandler.ServeHTTP({0x140001e1e30?}, {0x1038f9b80, 0x140006500e0}, 0x1400035c100)
	/usr/local/go/src/net/http/server.go:2936 +0x2d8
net/http.(*conn).serve(0x14000735b00, {0x1038fb378, 0x140005b91a0})
	/usr/local/go/src/net/http/server.go:1995 +0x560
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:3089 +0x520

```

**Comment by geoknee** [comment]
Duplicate of #1209
