### ISSUE TITLE
Handle websocket connection being closed by browser

### ISSUE THREAD

**Issue by lalexgap** [statechannels/go-nitro#1291]
When a rpc websocket connection is closed abruptly (say by closing/refreshing page) it results in an ugly error being printed out. This doesn't actually seem to stop the server from accepting new connections / servicing requests but it would still be nice to handle it, so it doesn't pollute the log. 
```
2023/05/17 15:42:04 http: panic serving 127.0.0.1:56396: failed to get reader: received close frame: status = StatusGoingAway and reason = ""
goroutine 167 [running]:
net/http.(*conn).serve.func1()
	/opt/homebrew/Cellar/go/1.20.4/libexec/src/net/http/server.go:1854 +0xb0
panic({0x10641a580, 0x1400016fd40})
	/opt/homebrew/Cellar/go/1.20.4/libexec/src/runtime/panic.go:890 +0x258
github.com/statechannels/go-nitro/rpc/transport/ws.(*serverWebSocketTransport).subscribe(0x14000112340, {0x1066370b0?, 0x140000fe0e0?}, 0x140002c2500)
	/Users/lagap/code/go-nitro/rpc/transport/ws/server.go:151 +0x430
net/http.HandlerFunc.ServeHTTP(0x14000478ad8?, {0x1066370b0?, 0x140000fe0e0?}, 0x10?)
	/opt/homebrew/Cellar/go/1.20.4/libexec/src/net/http/server.go:2122 +0x38
net/http.(*ServeMux).ServeHTTP(0x0?, {0x1066370b0, 0x140000fe0e0}, 0x140002c2500)
	/opt/homebrew/Cellar/go/1.20.4/libexec/src/net/http/server.go:2500 +0x140
net/http.serverHandler.ServeHTTP({0x14000519ce0?}, {0x1066370b0, 0x140000fe0e0}, 0x140002c2500)
	/opt/homebrew/Cellar/go/1.20.4/libexec/src/net/http/server.go:2936 +0x2d8
net/http.(*conn).serve(0x140005f8c60, {0x106638938, 0x140005a4660})
	/opt/homebrew/Cellar/go/1.20.4/libexec/src/net/http/server.go:1995 +0x560
created by net/http.(*Server).Serve
	/opt/homebrew/Cellar/go/1.20.4/libexec/src/net/http/server.go:3089 +0x520
```

**Comment by geoknee** [comment]
> his doesn't actually seem to stop the server from accepting new connections / servicing requests

https://github.com/golang/go/issues/16542 `net/http` package will recover from panics triggered in handlers.
