### ISSUE TITLE
Concurrent Map read and map write in MockChain

### ISSUE THREAD

**Issue by NiloCK** [statechannels/go-nitro#1398]
Recent CI run against a comments-only change set: https://github.com/statechannels/go-nitro/actions/runs/5423048162/jobs/9860465199

[https://github.com/statechannels/go-nitro/actions/runs/5423048162/jobs/9860465199#step:7:2159](Line 2159): fatal error: concurrent map read and map write

The output is the less-useful style with a dump of all running goroutines. I do not know whether the immediately following goroutine (Mockchain.SubmitTransaction) is the source of the error. (After inspection: seems likely. "Running" goroutine, line number, error type make sense together.)

**Comment by NiloCK** [comment]
The error text and its immediate surroundings, for posterity (the GH action results disappear after some time).

```
"level":"trace","node":"0x2B5AD5c4795c026514f8317c7a215E218DcCD6cF","rpc":"server","scope":"","time":1688129270415,"message":"Sending notification: DirectFunding-0x2c6f50b070cda42d1d61e7661b12f7bcd6e374adf58874ef39d376873521f185"}
{"level":"trace","node":"0x2B5AD5c4795c026514f8317c7a215E218DcCD6cF","rpc":"server","scope":"","time":1688129270415,"message":"Sending notification: {ID:0x2c6f50b070cda42d1d61e7661b12f7bcd6e374adf58874ef39d376873521f185 Status:Open Balance:{AssetAddress:0x0000000000000000000000000000000000000000 Me:0x2B5AD5c4795c026514f8317c7a215E218DcCD6cF Them:0x7E5F4552091A69125d5DfCb7b8C2659029395Bdf MyBalance:0x64 TheirBalance:0x64}}"}
{"level":"debug","engine":"0x6813Eb","time":1688129270416,"caller":"engine.go:612","message":"Objective DirectFunding-0x51f0e8caec5b10311a675568b66fef1483e3ea64db593983d3ba4e34e08810c5 is WaitingForCompleteFunding"}
{"level":"trace","engine":"0x2B5AD5","To":"0x2B5AD5","From":"0x6813Eb","PayloadSummaries":[{"ObjectiveId":"DirectFunding-0x191e8e0ab2b14788d2f790e926eda93ce29eea2ffe7271656bee688b022768b8","Type":"SignedStatePayload","PayloadDataSize":803}],"ProposalSummaries":[],"Payments":[],"RejectedObjectives":[],"time":1688129270416,"caller":"engine.go:840","message":"Received message"}
{"level":"debug","engine":"0x2B5AD5","time":1688129270416,"caller":"engine.go:612","message":"Objective DirectFunding-0x191e8e0ab2b14788d2f790e926eda93ce29eea2ffe7271656bee688b022768b8 is WaitingForCompleteFunding"}
{"level":"debug","engine":"0x2B5AD5","time":1688129270416,"caller":"engine.go:572","message":"Sending chain transaction for channel 0x191e8e0ab2b14788d2f790e926eda93ce29eea2ffe7271656bee688b022768b8"}
{"level":"debug","engine":"0x1efF47","time":1688129270417,"caller":"engine.go:421","message":"handling chain event: Deposited 100 units of 0x0000000000000000000000000000000000000000 token leaving 100 now held against channel 0x51f0e8caec5b10311a675568b66fef1483e3ea64db593983d3ba4e34e08810c5 at Block 4"}
{"level":"debug","engine":"0x1efF47","time":1688129270417,"caller":"engine.go:612","message":"Objective DirectFunding-0x51f0e8caec5b10311a675568b66fef1483e3ea64db593983d3ba4e34e08810c5 is WaitingForCompleteFunding"}
{"level":"debug","engine":"0x1efF47","time":1688129270417,"caller":"engine.go:572","message":"Sending chain transaction for channel 0x51f0e8caec5b10311a675568b66fef1483e3ea64db593983d3ba4e34e08810c5"}
fatal error: concurrent map read and map write

goroutine 3840 [running]:
github.com/statechannels/go-nitro/node/engine/chainservice.(*MockChain).SubmitTransaction(0xc000b14690, {0x1f0cb40?, 0xc000bb41f8?})
	/home/runner/work/go-nitro/go-nitro/node/engine/chainservice/mock_chain.go:39 +0x10e
github.com/statechannels/go-nitro/node/engine/chainservice.(*MockChainService).SendTransaction(0x18a18a0?, {0x1f0cb40?, 0xc000bb41f8?})
	/home/runner/work/go-nitro/go-nitro/node/engine/chainservice/mock_chainservice.go:26 +0x26
github.com/statechannels/go-nitro/node/engine.(*Engine).executeSideEffects(0xc0001744b0, {{0x0, 0x0, 0x0}, {0xc00131d660, 0x1, 0x1}, {0x0, 0x0, 0x0}})
	/home/runner/work/go-nitro/go-nitro/node/engine/engine.go:573 +0x21e
github.com/statechannels/go-nitro/node/engine.(*Engine).attemptProgress(0xc0001744b0, {0x1f25038, 0xc00067f8c0})
	/home/runner/work/go-nitro/go-nitro/node/engine/engine.go:628 +0xabd
github.com/statechannels/go-nitro/node/engine.(*Engine).handleChainEvent(0xc0001744b0, {0x1f0cb00?, 0xc000b3a780})
	/home/runner/work/go-nitro/go-nitro/node/engine/engine.go:438 +0x2a6
github.com/statechannels/go-nitro/node/engine.(*Engine).run(0xc0001744b0, {0x1f17300, 0xc000bbbb30})
	/home/runner/work/go-nitro/go-nitro/node/engine/engine.go:210 +0x5a5
created by github.com/statechannels/go-nitro/node/engine.New
	/home/runner/work/go-nitro/go-nitro/node/engine/engine.go:170 +0xb4a

goroutine 1 [chan receive]:
testing.(*T).Run(0xc0004189c0, {0x1a61534?, 0x53e605?}, 0x1cfe030)
	/opt/hostedtoolcache/go/1.20.0/x64/src/testing/testing.go:1630 +0x405
testing.runTests.func1(0x2d21540?)
	/opt/hostedtoolcache/go/1.20.0/x64/src/testing/testing.go:2036 +0x45
testing.tRunner(0xc0004189c0, 0xc00029fc88)
	/opt/hostedtoolcache/go/1.20.0/x64/src/testing/testing.go:1576 +0x10b
testing.runTests(0xc00045bd60?, {0x2a29020, 0x6, 0x6}, {0x2?, 0x100c00029fd10?, 0x2d1fb20?})
	/opt/hostedtoolcache/go/1.20.0/x64/src/testing/testing.go:2034 +0x489
testing.(*M).Run(0xc00045bd60)
	/opt/hostedtoolcache/go/1.20.0/x64/src/testing/testing.go:1906 +0x63a
main.main()
	_testmain.go:57 +0x1aa
```

**Comment by NiloCK** [comment]
Maybe `MockChain.holdings` wants to be a safesync map instead?

https://github.com/statechannels/go-nitro/blob/d5feab74e34ecf95e231cd92eeb796c1965f1ff4/node/engine/chainservice/mock_chain.go#L39

**Comment by geoknee** [comment]
> Maybe `MockChain.holdings` wants to be a safesync map instead? This is the line that caused the error. Type of `holdings` is `map[types.Destination]types.Funds`
> 
> https://github.com/statechannels/go-nitro/blob/d5feab74e34ecf95e231cd92eeb796c1965f1ff4/node/engine/chainservice/mock_chain.go#L39

Almost certainly yes. We've done that switch many times in the past and it should resolve the problem.
