### ISSUE TITLE
`panic: send on a closed channel` in rpc/nats test

### ISSUE THREAD

**Issue by geoknee** [statechannels/go-nitro#1464]
Unrelated change to docs triggered this failure: 
https://github.com/statechannels/go-nitro/actions/runs/5586952166/jobs/10211640672?pr=1463
```
=== RUN   TestRPCWithManualVoucherExchange/4_clients#01
    rpc_test.go:200: Ledger channels queried
    rpc_test.go:257: Payment channels queried
    rpc_test.go:288: Vouchers sent/received
    rpc_test.go:303: Ledger/virtual channels closed
panic: send on closed channel

goroutine 5633 [running]:
github.com/statechannels/go-nitro/rpc/transport/nats.(*natsTransportClient).Subscribe.func1(0x11c19cc?)
	/home/runner/work/go-nitro/go-nitro/rpc/transport/nats/client.go:56 +0x2a
github.com/nats-io/nats%2ego.(*Conn).waitForMsgs(0xc00086c600, 0xc000948820)
	/home/runner/go/pkg/mod/github.com/nats-io/nats.go@v1.21.0/nats.go:2884 +0x442
created by github.com/nats-io/nats%2ego.(*Conn).subscribeLocked

```

[integration-test-logs (5).zip](https://github.com/statechannels/go-nitro/files/12080006/integration-test-logs.5.zip)

**Comment by geoknee** [comment]
Closing as I don't think we have seen this in quite a while.
