### ISSUE TITLE
Simple TCP Message Service often fails under load

### ISSUE THREAD

**Issue by lalexgap** [statechannels/go-nitro#717]
```
May 25 17:11:29.932165	INFO	1.8248s      ERROR << single[003] >> panic: write tcp 127.0.0.1:64844->127.0.0.1:7001: write: broken pipe
May 25 17:11:29.957307	INFO	1.8499s      ERROR << single[003] >>
May 25 17:11:29.957363	INFO	1.8500s      ERROR << single[003] >> goroutine 28 [running]:
May 25 17:11:29.957386	INFO	1.8500s      ERROR << single[003] >> github.com/statechannels/go-nitro/client/engine/messageservice/simple-tcp.(*SimpleTCPMessageService).panicIfRunning(0x140000101a0?, {0x100bf1fa8?, 0x1400051a500})
May 25 17:11:29.957395	INFO	1.8500s      ERROR << single[003] >> 	/Users/lagap/go/pkg/mod/github.com/statechannels/go-nitro@v0.0.0-20220524172027-e876750be91c/client/engine/messageservice/simple-tcp/simpletcp-messageservice.go:131 +0x60
May 25 17:11:29.957403	INFO	1.8500s      ERROR << single[003] >> github.com/statechannels/go-nitro/client/engine/messageservice/simple-tcp.(*SimpleTCPMessageService).listenForOutgoing(0x140000b46c0)
May 25 17:11:29.957422	INFO	1.8501s      ERROR << single[003] >> 	/Users/lagap/go/pkg/mod/github.com/statechannels/go-nitro@v0.0.0-20220524172027-e876750be91c/client/engine/messageservice/simple-tcp/simpletcp-messageservice.go:85 +0x1f4
May 25 17:11:29.958020	INFO	1.8506s      ERROR << single[003] >> created by github.com/statechannels/go-nitro/client/engine/messageservice/simple-tcp.NewSimpleTCPMessageService
May 25 17:11:29.958030	INFO	1.8507s      ERROR << single[003] >> 	/Users/lagap/go/pkg/mod/github.com/statechannels/go-nitro@v0.0.0-20220524172027-e876750be91c/client/engine/messageservice/simple-tcp/simpletcp-messageservice.go:47 +0x1bc
May 25 17:11:29.958064	INFO	1.8507s INCOMPLETE << single[003] >>
May 25 17:11:29.962160	INFO	1.8547s      ERROR << single[001] >> panic: dial tcp 127.0.0.1:7003: connect: connection refused
May 25 17:11:29.993166	INFO	1.8858s      ERROR << single[001] >>
May 25 17:11:29.993286	INFO	1.8859s      ERROR << single[001] >> goroutine 76 [running]:
May 25 17:11:29.993301	INFO	1.8859s      ERROR << single[001] >> github.com/statechannels/go-nitro/client/engine/messageservice/simple-tcp.(*SimpleTCPMessageService).panicIfRunning(0x100b7143a?, {0x100d65fa8?, 0x14000136cd0})
May 25 17:11:29.993309	INFO	1.8859s      ERROR << single[001] >> 	/Users/lagap/go/pkg/mod/github.com/statechannels/go-nitro@v0.0.0-20220524172027-e876750be91c/client/engine/messageservice/simple-tcp/simpletcp-messageservice.go:131 +0x60
May 25 17:11:29.993315	INFO	1.8859s      ERROR << single[001] >> github.com/statechannels/go-nitro/client/engine/messageservice/simple-tcp.(*SimpleTCPMessageService).listenForOutgoing(0x14000306630)
May 25 17:11:29.993324	INFO	1.8860s      ERROR << single[001] >> 	/Users/lagap/go/pkg/mod/github.com/statechannels/go-nitro@v0.0.0-20220524172027-e876750be91c/client/engine/messageservice/simple-tcp/simpletcp-messageservice.go:80 +0x214
May 25 17:11:29.993392	INFO	1.8860s      ERROR << single[001] >> created by github.com/statechannels/go-nitro/client/engine/messageservice/simple-tcp.NewSimpleTCPMessageService
May 25 17:11:29.993402	INFO	1.8860s      ERROR << single[001] >> 	/Users/lagap/go/pkg/mod/github.com/statechannels/go-nitro@v0.0.0-20220524172027-e876750be91c/client/engine/messageservice/simple-tcp/simpletcp-messageservice.go:47 +0x1bc
May 25 17:11:29.994047	INFO	1.8867s INCOMPLETE << single[001] >>
May 25 17:11:30.033555	INFO	1.9262s      ERROR << single[002] >> panic: dial tcp 127.0.0.1:7001: connect: connection refused
May 25 17:11:30.061657	INFO	1.9543s      ERROR << single[000] >> panic: dial tcp 127.0.0.1:7001: connect: connection refused
May 25 17:11:30.067051	INFO	1.9597s      ERROR << single[002] >>
May 25 17:11:30.067085	INFO	1.9597s      ERROR << single[000] >>
May 25 17:11:30.067131	INFO	1.9598s      ERROR << single[000] >> goroutine 83 [running]:
May 25 17:11:30.067151	INFO	1.9598s      ERROR << single[002] >> goroutine 74 [running]:
May 25 17:11:30.067335	INFO	1.9600s      ERROR << single[000] >> github.com/statechannels/go-nitro/client/engine/messageservice/simple-tcp.(*SimpleTCPMessageService).panicIfRunning(0x100b2543a?, {0x100d19fa8?, 0x1400015e320})
May 25 17:11:30.067407	INFO	1.9600s      ERROR << single[000] >> 	/Users/lagap/go/pkg/mod/github.com/statechannels/go-nitro@v0.0.0-20220524172027-e876750be91c/client/engine/messageservice/simple-tcp/simpletcp-messageservice.go:131 +0x60
May 25 17:11:30.067423	INFO	1.9601s      ERROR << single[000] >> github.com/statechannels/go-nitro/client/engine/messageservice/simple-tcp.(*SimpleTCPMessageService).listenForOutgoing(0x1400040e0c0)
May 25 17:11:30.067429	INFO	1.9601s INCOMPLETE << single[000] >>
May 25 17:11:30.067436	INFO	1.9601s INCOMPLETE << single[002] >>
May 25 17:11:30.067443	INFO	1.9601s      ERROR << single[002] >> github.com/statechannels/go-nitro/client/engine/messageservice/simple-tcp.(*SimpleTCPMessageService).panicIfRunning(0x102bd143a?, {0x102dc5fa8?, 0x140000eb220})
May 25 17:11:30.067455	INFO	1.9601s      ERROR << single[002] >> 	/Users/lagap/go/pkg/mod/github.com/statechannels/go-nitro@v0.0.0-20220524172027-e876750be91c/client/engine/messageservice/simple-tcp/simpletcp-messageservice.go:131 +0x60
May 25 17:11:30.067463	INFO	1.9601s      ERROR << single[002] >> github.com/statechannels/go-nitro/client/engine/messageservice/simple-tcp.(*SimpleTCPMessageService).listenForOutgoing(0x14000307320)
May 25 17:11:30.067479	INFO	1.9601s      ERROR << single[000] >> 	/Users/lagap/go/pkg/mod/github.com/statechannels/go-nitro@v0.0.0-20220524172027-e876750be91c/client/engine/messageservice/simple-tcp/simpletcp-messageservice.go:80 +0x214
May 25 17:11:30.067491	INFO	1.9601s      ERROR << single[000] >> created by github.com/statechannels/go-nitro/client/engine/messageservice/simple-tcp.NewSimpleTCPMessageService
May 25 17:11:30.067498	INFO	1.9601s      ERROR << single[000] >> 	/Users/lagap/go/pkg/mod/github.com/statechannels/go-nitro@v0.0.0-20220524172027-e876750be91c/client/engine/messageservice/simple-tcp/simpletcp-messageservice.go:47 +0x1bc
May 25 17:11:30.067522	INFO	1.9602s      ERROR << single[002] >> 	/Users/lagap/go/pkg/mod/github.com/statechannels/go-nitro@v0.0.0-20220524172027-e876750be91c/client/engine/messageservice/simple-tcp/simpletcp-messageservice.go:80 +0x214
May 25 17:11:30.067528	INFO	1.9602s      ERROR << single[002] >> created by github.com/statechannels/go-nitro/client/engine/messageservice/simple-tcp.NewSimpleTCPMessageService
May 25 17:11:30.067533	INFO	1.9602s      ERROR << single[002] >> 	/Users/lagap/go/pkg/mod/github.com/statechannels/go-nitro@v0.0.0-20220524172027-e876750be91c/client/engine/messageservice/simple-tcp/simpletcp-messageservice.go:47 +0x1bc
```

In this case the error appears to be a `broken pipe`? In general the simple TCP message seems to fail often with tcp related errors under load.

**Comment by lalexgap** [comment]
We've now switched to the p2p message service.
